### ISSUE TITLE
Mi primera clase

### ISSUE THREAD

**Issue by evaristor** [IslasGECI/ejemplo_para_andrea#6]
Programa la primera clase en R6. [Aquí](https://adv-r.hadley.nz/r6.html#r6-classes) podrás encontrar algo similar a la prueba y al inicio del capítulo verás cómo definir las clases.

**Comment by evaristor** [comment]
Transferí este _issue_ [#16](https://github.com/IslasGECI/dimorfismo/issues/16) de **dimorfismo**

**Comment by andrea-sanchez** [comment]
Este ejemplo didáctico se cerró con este `feature/tests_my_class` [aquí](https://github.com/IslasGECI/ejemplo_para_andrea/commit/be9496085da7d7cfc3921ad46f9118319067b3ba).
@nepito hay algo más que hacer aquí?

**Comment by evaristor** [comment]
Se ve bien.
:100: :+1:
